---
title: "Pilot data analysis"
output:
  html_document:
    df_print: paged
editor_options: 
  chunk_output_type: console
---

```{r}
library(lmerTest)
library(tidyverse)
library(cowplot)
library(stargazer)
source("RainCloudPlots.R")

# explore counterbalancing condition
counterbalancing <- fs::dir_ls(path = "./data", glob = "*.csv") %>%
  map_dfr(read_csv, .id = "source", n_max = 1, col_type = cols(
  .default = col_character(), rt = col_double(), corr = col_integer(), TrialID = col_integer()))

exp1 <- read_csv("Exp 1 data.csv")
exp1$device <- ifelse(exp1$OS %in% c("Linux armv7l", "Linux armv8l"), "android", "computer")

csv_data <- fs::dir_ls(path = "./data", glob = "*.csv") %>%
  map_dfr(read_csv, .id = "source", col_type = cols(
  .default = col_character(), rt = col_double(), corr = col_integer(), TrialID = col_integer())) %>% 
  filter(!is.na(TrialID) & TrialID < 1000) %>%
  select(source, participant, date, OS, frameRate, rt, corr, TrialID, StimulusType, Condition, PrimeDuration, Prime, Target)

csv_data$device <- ifelse(csv_data$OS %in% c("Linux armv7l", "Linux armv8l"), "android", "computer")

# get participants with correct responses

accuracy_by_participant <- csv_data %>% group_by(source) %>% summarise(acc = mean(corr == 1), N = n()) %>% left_join(counterbalancing, by = "source")


  
participants_to_include <- accuracy_by_participant %>% filter(N == 480 & acc > .8)   

participants_to_exclude <- accuracy_by_participant %>% filter(N != 480 | acc <= .8)   

#participants_to_exclude[,1:3]

participant_list_for_prolific <- str_extract(string = participants_to_include$source, pattern = "[a-z0-9]{24}") 


paste0(participant_list_for_prolific, sep = "\n") %>% writeClipboard() # works on windows

exclude_list_for_prolific <- str_extract(string = participants_to_exclude$source, pattern = "[a-z0-9]{24}") %>% paste0(collapse = "\n")

# for now, we only have two participants with accuracy > .8 and a full data set

exp2_data_to_include <- csv_data %>% filter(source %in% participants_to_include$source) %>% mutate(StimulusType = StimulusType %>% factor, Condition = Condition %>% factor, PrimeDuration = PrimeDuration %>% factor, rt = rt * 1000)

exp1_data_to_include <- exp1 %>% mutate(StimulusType = StimulusType %>% factor, Condition = Condition %>% factor, PrimeDuration = PrimeDuration %>% factor)

write_csv(exp2_data_to_include, file = "exp2_current_data.csv")

exp1_data_summary_rt <- exp1_data_to_include %>% group_by(StimulusType, Condition, PrimeDuration) %>% summarise(M = mean(rt), SD = sd(rt), N = n())

exp2_data_summary_rt <- exp2_data_to_include %>% group_by(StimulusType, Condition, PrimeDuration) %>% summarise(M = mean(rt), SD = sd(rt), N = n())

# data above 1500 ms excluded

plot_raincloud(exp1_data_to_include %>% filter(corr == 1 & rt < 1500), x_column = "Condition", y_column = "rt", x_label = "Condition", y_label = "RT in ms (correct responses)", main_title = "RT by condition and word type (Experiment 1)") + 
  # put labels on the mean for easier comparison
  stat_summary(fun.data = function(x) {data.frame(label = format(mean(x), digits = 2), y = mean(x))}, 
                                      geom = "text",
                                      #width = 1,
                                      position = position_nudge(x = 0.5, y = 0),
                                      #size = 0.2,
                                      color = "black") +
  facet_grid(cols = vars(PrimeDuration), rows = vars(StimulusType), labeller = label_context)

plot_raincloud(exp2_data_to_include %>% filter(corr == 1 & rt < 1500), x_column = "Condition", y_column = "rt", x_label = "Condition", y_label = "RT in ms (correct responses)", main_title = "RT by condition and word type (Experiment 2)") + 
  # put labels on the mean for easier comparison
  stat_summary(fun.data = function(x) {data.frame(label = format(mean(x), digits = 2), y = mean(x))}, 
                                      geom = "text",
                                      #width = 1,
                                      position = position_nudge(x = 0.5, y = 0),
                                      #size = 0.2,
                                      color = "black") +
  facet_grid(cols = vars(PrimeDuration), rows = vars(StimulusType), labeller = label_context)





```

## LMM for RT (words, correct responses)

```{r lmm1}
contrasts(exp1_data_to_include$Condition) <- c(-1,1)
contrasts(exp1_data_to_include$PrimeDuration) <- c(-1,1)
lmm_exp1 <- lmer(data = exp1_data_to_include %>% filter(corr == 1 & StimulusType == "WORD" & rt > 250 & rt < 2000), rt ~ Condition * PrimeDuration + (1|source) + (1|Target))

summary(lmm_exp1)

```

```{r lmm2}
contrasts(exp2_data_to_include$Condition) <- c(-1,1)
contrasts(exp2_data_to_include$PrimeDuration) <- c(-1,1)

lmm_exp2 <- lmer(data = exp2_data_to_include %>% filter(corr == 1 & StimulusType == "WORD" & rt > 250 & rt < 2000), rt ~ Condition * PrimeDuration + (1|source) + (1|Target))

summary(lmm_exp2)

```

gLMM for accuracy (Words)

```{r logistic_lmm_exp1}

lmm_acc_exp1 <- glmer(data = exp1_data_to_include %>% filter(corr != -1 & StimulusType == "WORD" & rt < 1500), corr ~ Condition * PrimeDuration + (1|Target), family = binomial(link = "logit"))

summary(lmm_acc_exp1)

```

```{r logistic_lmm_exp2}

lmm_acc_exp2 <- glmer(data = exp2_data_to_include %>% filter(corr != -1 & StimulusType == "WORD" & rt < 1500), corr ~ Condition * PrimeDuration + (1|Target), family = binomial(link = "logit"))

summary(lmm_acc_exp2)

```

BRMS analysis

```{r brms}
library(brms)
#ncores = parallel::detectCores()
# Mean RTs in each condition

prior_exp1 <- c(set_prior("normal(0,100)", class = "b", coef = "Condition1"),
            set_prior("normal(0,100)", class = "b", coef = "Condition1:PrimeDuration1"),
            set_prior("normal(0,100)", class = "b", coef = "PrimeDuration1"))
  

blmm_exp1_acc <- brm(data = exp1_data_to_include %>% filter(corr != -1 & StimulusType == "WORD" & rt > 250 & rt < 2000), 
                 formula = corr ~ Condition * PrimeDuration + (1 + Condition * PrimeDuration|source) + (1 + Condition * PrimeDuration|Target),
                 warmup = 1000,
                 iter = 5000,
                 chains = 4,
                 prior = prior_exp1,
                 family = bernoulli(link = "logit"),
                 inits = "random",
                 control = list(adapt_delta = 0.95),
                 cores = 4, backend = "cmdstanr", threads = threading(2))

save(blmm_exp1_acc, file = "blmm_exp1_acc_new.RData")

                 #blmm_exp1_full <- update(blmm_exp1,
#                         warmup = 1000,
#                         iter = 5000, 
#                         chains = 4,
#                         prior = prior_exp1,
#                         family = exgaussian(),
#                         inits = "random",
#                         control = list(adapt_delta = 0.95),
#                         cores = 4, 
#                         backend = "cmdstanr", 
#                         threads = threading(2))


#save(blmm_exp2, file = "blmm_exp2.RData")

blmm_exp1_rt <- brm(data = exp1_data_to_include %>% filter(corr == 1 & StimulusType == "WORD" & rt > 250 & rt < 2000), 
                        rt ~ Condition * PrimeDuration + (1 + Condition * PrimeDuration|source) + (1 + Condition * PrimeDuration|Target),
                        warmup = 1000,
                        iter = 5000,
                        chains = 4,
                        prior = prior_exp1,
                        family = exgaussian(),
                        inits = "random",
                        control = list(adapt_delta = 0.95),
                        cores = 4, backend = "cmdstanr", threads = threading(2))

save(blmm_exp1_rt, file = "blmm_exp1_rt_new.RData")

```
